import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";

import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Next.js API + Postgres Example",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />

        <h1>Dogs!</h1>

        {children}

        <AppFooter />
      </body>
    </html>
  );
};

export default RootLayout;
